"""Adicionando coluna quantidade na tabela purchase_orders

Revision ID: 0a674651c22b
Revises:
Create Date: 2025-04-07 15:14:40.931218

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a674651c22b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'purchase_orders',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('description', sa.String(length=500), nullable=False),
    )
    op.create_table(
        'purchase_orders_items',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('price', sa.REAL(), nullable=False),
        sa.Column('purchase_order_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id']),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column(
            'price', existing_type=sa.REAL(), type_=sa.Float(precision=2), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column(
            'price', existing_type=sa.Float(precision=2), type_=sa.REAL(), existing_nullable=False
        )

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
    op.drop_table('purchase_orders_items')
    op.drop_table('purchase_orders')
