"""users table

Revision ID: 7b134dfa54cd
Revises: f606aa9493f1
Create Date: 2025-05-08 15:46:44.727017

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b134dfa54cd'
down_revision = 'f606aa9493f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column(
            'price', existing_type=sa.REAL(), type_=sa.Float(precision=2), existing_nullable=False
        )

    # ### end Alembic commands ###
    # Versões anteriores da aplicação podiam criar esta tabela antes da migração.
    if not sa.inspect(op.get_bind()).has_table('users'):
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('email', sa.String(length=100), nullable=False),
            sa.Column('password', sa.String(length=300), nullable=False),
            sa.UniqueConstraint('email'),
        )


def downgrade():
    # This revision may have adopted an existing users table, so its origin is
    # ambiguous during downgrade. Keep it to avoid deleting legacy accounts.

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.alter_column(
            'price', existing_type=sa.Float(precision=2), type_=sa.REAL(), existing_nullable=False
        )

    # ### end Alembic commands ###
